name: Celebrate changed files

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  find-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          # Needed to detect changed files
          fetch-depth: 2

      - name: Get updated docs
        if: ${{ github.event_name == 'push' }}
        id: changed-files
        uses: tj-actions/changed-files@716b1e13042866565e00e85fd4ec490e186c4a2f # pin @v41.0.1
        with:
          fetch_depth: 2
          files: docs/**/*.{md,mdx}
          files_ignore: docs/news/_template.md
          json: false

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Debug what files changed
        env:
          FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          DELETED_FILES: ${{ steps.changed-files.outputs.deleted_files }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #ROOT: ../../..
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          echo "${FILES}"
          python -c "import os; print(repr(os.environ['FILES']))"
